"use client";
import Footer from "@/components/additional/Footer";
import "./globals.css";
import { Inter } from "next/font/google";
import { StateProvider } from "@/context/StateContext";
import reducer, { initialState } from "@/context/StateReducers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StateProvider initialState={initialState} reducer={reducer}>
        <div className={inter.className}>{children}</div>
        <Footer />
      </StateProvider>
    </html>
  );
}
